#!/bin/sh

composer="`which -a composer | awk 'NR==2 {print}'`"
if [ "$composer" = "" ]; then
    echo "composer executable not found"
    exit 1
fi

if [ `whoami` == "root" ]; then
    directory="`pwd`"
    user="`ls -ld  ${directory} | awk '{ print $3 }'`"
    group="`ls -ld  ${directory} | awk '{ print $4 }'`"

    su-exec ${user}:${group} ${composer} "${@}"
else
    ${composer} "${@}"
fi
